version: '3'
services:
  web:
    container_name: ${PROJECT_NAME}-web
    build:
      context: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    restart: always
    ports:
      - '80:3000'
    networks:
      default: {}

networks:
  default:
    driver: bridge
